{% set name = "libNeuroML" %}
{% set version = "0.6.6" %}
{% set sha256 = "45251737558703d88af85d51dbe874d7bb3dd8bd9142f8b224bc7ca00698d42f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.lower() }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - six
    - lxml
    - pytables >=3.3.0
    - jsonpickle >=0.9.6
    - pymongo
    - numpy <2.0.0
    - numexpr
    - networkx
    - natsort

test:
  requires:
    - python {{ python_min }}
  imports:
    - neuroml
    - neuroml.nml
    - neuroml.hdf5

about:
  home: https://github.com/NeuralEnsemble/libNeuroML
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A Python library for working with neuronal models specified in NeuroML 2
  dev_url: https://github.com/NeuralEnsemble/libNeuroML
  doc_url: http://libneuroml.readthedocs.io/

extra:
  recipe-maintainers:
    - pgleeson
    - mstimberg
    - kapilkd13
