{% set name = "libNeuroML" %}
{% set version = "0.5.4" %}
{% set sha256 = "ac478fbd9a7a1dfa495ca305b4f434412643d05623adc1c7d5c0c4618d9416ad" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - six
    - lxml
    - pytables >=3.3.0
    - jsonpickle >=0.9.6
    - pymongo
    - numpy
    - numexpr
    - networkx

test:
  imports:
    - neuroml
    - neuroml.test
    - neuroml.nml
    - neuroml.hdf5

about:
  home: https://github.com/NeuralEnsemble/libNeuroML
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A Python library for working with neuronal models specified in NeuroML 2
  dev_url: https://github.com/NeuralEnsemble/libNeuroML
  doc_url: http://libneuroml.readthedocs.io/

extra:
  recipe-maintainers:
    - pgleeson
    - mstimberg
    - kapilkd13
