travis:
  secure:
    BINSTAR_TOKEN: E3Mc7eF2JsztP/TDyqCEbkLcPnXfWAZ2vvVlLFAHGpnjLcCRPqX7/0LwpK6UKRO3PEMVNYxDfD0b3HvEuNVJg0BYV9Q4z3Uui/hAYhjXib+l4W86gFwc8jVjsOBMc2T8yOXFOmwywOt+omRMhESrGR6wRe50kGmwlJIhYRR4A1zjBeUF3O1WlzN1PvNybFqs4IAwkVv3V/LrElc4qoYO4Ojdxw7JcOULSAPrYtkEl99jSRc8b+CUAzDCW3Mcl6+7+8WlPjG97zuqcvN/mV1+kZHpH24ir/Xnpi9V/3n9hDifcTkSDavadEJFbBQzKe5uIO6uLOEcxVqeqJKjQEXIxBC38dqynYXXZ4oITCl8sjOcrNOrePQmgiHt6WnHER4SMM8sB/oG2VO+Rnj4swCwshUbNLMO6naXYw9+eQhnf+wEbA9RW1FfXGT0+9lofHLzJb0SEICKJvIFyU6Out6ur/6kzf+Xh3KMlXaXYEyKKR6C+6IdtzYJgmPfumgDvO4TJcbyfdYdDxUjY7M0UNfH89jkusPHz88HbhCc4my1c4EUk/eNWA+WVYZ4S7JPnVuFwhO5zPPMEkhEolEq25aKW2sCO9RC3ICM8l2TezrZ+V66w2gh9ebKshuZ2oqrVv6tenQt1SoA03krv2dZ3qrxRGEWkSW/bDr7NGURYHDk83A=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
