travis:
  secure:
    BINSTAR_TOKEN: OSoBwGqymxOpk42TZhTj8xglPHltUR5daa0T1THUwsVA5zwA/jsFfJOc2Awf8hL4TfJIYBUh5YiLzinRb616TBSFi+zBVasEDDuxcQHRtwsQTwLskbgf15quwFEV8Z70yUq+nwBO1nn4agm5r/mXdDNtN7B8BwbIgGmJA/U7GdtkqazD6QlJLvRK4vlBgKnF/sZxJVvclahiNm45jtxrT7pngtc2eE2QEerVz+4wksoG/z6QbIKIHc+xMrI/oBS+G9zPxE5SfQX8HKOgFNQplqvqwXRil80aCOaDVpUBF278gUa4sSJcm2SLQBAuJjstcwEJuKE2MMoyJSkR6PAmdq77kAV3t6z+EaN4G7oLDRFFAQ3XJTVP77nbgSr4ms5tTkVUeDeTZ7IKLp0EBW2rrQ3b841rTKZzkWI6XVYCeE4WU3q9OKFSjvsBS/EVjqzFm7aEQCa6iuwYSyZMGiDRfSEIDbJeDlmh3sx1ODhQunXsGIT4eQwVV9CAvpvTMZxjZvJueng3LGtDNHJPVs3bclR8TLKGG/y+pJE72+K/aHTLiIcNGSwJtt0ttRRuXTyYX+/J4MQN0zz/LoAUo85iMsnDQyCPoXvHIxX2o53hzXVFCbzUfcLvV4k8nHxGKOWS3cwB1s1/ubX3YN8qNgrDEqI9Kz+3Z0EDVbxIKFJXq9E=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
